### ISSUE TITLE
I know it's the dark version, BUT THIS IS RIDICULOUS *laugh track

### ISSUE THREAD

**Issue by hdaustin616** [DirtDiglett/Pressure2#79] opened 2017-02-18 03:07 UTC
[####]Description of the issue.
When I open the skin, the entirety of my steam goes black 

#### Does it also occur on Steam without the skin installed?
yes

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
no

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
latest

#### A screenshot of the issue.
![screenshot 64](https://cloud.githubusercontent.com/assets/25857140/23089790/15737c4c-f544-11e6-95f8-26bd793f967c.png)

#### Steps to reproduce the issue.
just install the skin

**Comment by Js41637** [comment] 2017-02-18 03:23
Duplicate of #72 

> have you done a complete clear of your skin folder and reinstalled it from a fresh download? This usually happens with a corrupted download/Missing files.

**Closed as completed by Js41637** 2017-02-18 03:23 UTC
