### ISSUE TITLE
Fuzzy text in overlay, invisible message in pop-up

### ISSUE THREAD

**Issue by IAmNotMatthew** [DirtDiglett/Pressure2#35] opened 2016-03-05 06:57 UTC
#### Description of the issue.

Whenever I get a message from someone on my friend list it does not write the beginning of the message, only "XY says:" and then an open space below it, also, the font is stacking in the Steam overlay
#### Does it also occur on Steam without the skin installed?

It only occurs when I'm using Pressure2 and Air Skin, it does not occur when I'm using the default or any other skin.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

I'm in Steam Beta, it's the **same** without Steam Beta as well.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10
#### Are you using the latest stable release or using the latest commit version?

Yeah, the latest version.
#### A screenshot of the issue.

[Friends list](http://i.imgur.com/l6SL4uC.jpg)
[Web browser](http://i.imgur.com/Doyv945.jpg)
[Screenshots tab](http://i.imgur.com/SqbO4Ta.jpg)
#### Steps to reproduce the issue.

Well, open the Steam Overlay maybe.

**Comment by Asphira** [comment] 2016-03-05 08:58
The reason this occurs is because steam inside the ingame overlay deals with text rendering in a awkward terrible way, hence why in air and pressure 2 the 'font stacking' occurs. If it is on a light background (especially white) this is what it will do, from my understanding though Dirt is making an update where the overlay itself will be darker so the terrible font rendering from steams part won't be so bad.

Also are the chat notifications showing up correctly outside of the overlay? or are they not showing correctly for you at all?

**Comment by IAmNotMatthew** [comment] 2016-03-05 12:44
It shows up perfectly, only the beginning of the text is missing.
_EDIT: Multiple restarts after the text appeared in **black**._

**Comment by DirtDiglett** [comment] 2016-03-06 04:53
Duplicate of both #13 and #20 so i'm closing this one.

**Closed as completed by DirtDiglett** 2016-03-06 04:53 UTC
Labels: duplicate
