### ISSUE TITLE
Window completely black on Solus [Linux]

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure2#91] opened 2017-05-16 16:37 UTC
#### A screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/11262717/26117368/99e2764c-3a66-11e7-885b-ee45e281ac5f.png)

**Comment by j5lx** [comment] 2017-05-16 23:18
Duplicate of #72.

**Closed as completed** 2018-07-03 02:25 UTC
