### ISSUE TITLE
In-Game Overlay Friends List Button does not open friends list

### ISSUE THREAD

**Issue by big-mubble** [DirtDiglett/Pressure2#40] opened 2016-03-06 21:44 UTC
#### Description of the issue.

Friends button in the in-game overlay does not open friends list. Each of the other buttons work (Community Contributions, Guides, Active Discussions, and Screenshots), just not the friends list one.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 7
#### Are you using the latest stable release or using the latest commit version?

Yes
#### A screenshot of the issue.

![friendslistbugcap](https://cloud.githubusercontent.com/assets/17509340/13557251/e3dfb47e-e3b1-11e5-99ff-37e061371edc.jpg)
#### Steps to reproduce the issue.

Open the in-game overlay while in a game.

**Comment by DirtDiglett** [comment] 2016-03-06 23:04
Duplicate of #4 and #21 - This has been fixed for a 1.0.1 release.

**Closed as completed by DirtDiglett** 2016-03-06 23:05 UTC
Labels: duplicate
