### ISSUE TITLE
Search and Grey bars are not lined properly on Library in Detail View

### ISSUE THREAD

**Issue by BestPastelBR** [DirtDiglett/Pressure2#71] opened 2017-01-21 04:39 UTC
#### Description of the issue.
The images and menus on the library page in Detail View are not lined like in the images on the site and former versions, I know it's a silly thing but it's bugging me.

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Nope

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Latest stable, 1.0.2, released on 11/12/16

#### A screenshot of the issue.
http://imgur.com/a/QI3lo

#### Steps to reproduce the issue.
None, I guess.

**Comment by DirtDiglett** [comment] 2017-02-05 09:02
I'm honestly unsure of why this happens, and I can't reproduce it, so I doubt it will be fixed intentionally.

**Closed as completed** 2018-08-16 10:06 UTC
Labels: low priority bug
