### ISSUE TITLE
In Game Overlay

### ISSUE THREAD

**Issue by McManners** [DirtDiglett/Pressure2#29] opened 2016-03-01 23:51 UTC
#### Description of the issue.

When I turn on the overlay during gameplay the friends list option is cut in half
#### Does it also occur on Steam without the skin installed?

No
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

I'am not in the steam beta
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10
#### Are you using the latest stable release or using the latest commit version?

Latest Stable Version
#### A screenshot of the issue.

![2016-03-01 2](https://cloud.githubusercontent.com/assets/17581132/13446098/2d9bc024-dfd6-11e5-82ea-b3a096bf16aa.png)

**Comment by DirtDiglett** [comment] 2016-03-02 00:08
Duplicate of #4 and has already been fixed for a 1.0.1 bugfix release. Closing.

**Closed as completed by DirtDiglett** 2016-03-02 00:08 UTC
Labels: duplicate
