### ISSUE TITLE
My issues.

### ISSUE THREAD

**Issue by YomioniTio** [DirtDiglett/Pressure2#9] opened 2016-02-24 15:03 UTC
**Does it also occur on Steam without the skin installed?**

Nope.

**Are you in the Steam BETA?**

Nope.

**A screenshot of the issue.**
1. Black space on Update News Dialog. Is this black space supposed to be here? http://i.imgur.com/fWSuHAg.jpg
2. Friends button clicking area is a bit longer than it looks http://i.imgur.com/AW7iWcc.jpg
3. Is this space's there on purpose? (Large notifications)  http://i.imgur.com/9Wz4k4I.jpg
4. Space under and over the "You're currently offline" sign and Sing in button... http://i.imgur.com/V7tBa0M.jpg (See issue #2)
5. METASCORE score is barely visible http://i.imgur.com/1h9VBfy.jpg
6. Notification no new messages text hard to read http://i.imgur.com/KzD4u9r.jpg

**Comment by YomioniTio** [comment] 2016-02-24 15:05
And can we have a "View players" button in-game?

**Comment by katanacrimson** [comment] 2016-02-24 16:43
Space around the "You're currently offline" is covered by #2.

**Comment by Js41637** [comment] 2016-02-24 22:46
Edited your comment to make it clearer.
1. Black Space, unfortunately I don't think there isn't anything we can do about it, all news messages can be any height and I don't think we can change the background.
3. I assume you're talking about larger notifications? I _think_ the notifications in Pressure2 are a bit larger than normal, I think Dirt was making a tweak so you can choose what size.
4. Dupe of issue #2

**Comment by DirtDiglett** [comment] 2016-02-25 00:05
Hi @JoeSaunders and thanks for your report.

I'll respond to each part individually:
1. Unfortunately yes, the black space is meant to be there. I have done some clever trickery to be able to theme the updates webpage portion, but it is limited in what I can reliably theme there. The black is part of the background or <body> in the html, and I cannot modify this without it affected every single webpage you see in Steam.
2. That's intentional, oddly enough I found myself somehow missing that button by a few pixels to the left often enough to add that bit of extra forgiveness.
3.  Yes and No. I'd prefer to not have the extra vertical space, and only have them longer than default Steam's notification, but unfortunately making them longer causes a bug that makes the notifications magically grow taller as well. So I embraced the extra vertical space on most notifications, but ones with only two lines of text will look a little empty at the bottom. On the added bonus, they match Google's Material Design specifications better this way.
4. Yes, I am aware of this and fixing it as part of Issue #2 
5. This is to resolve that when a line is highlighted the Metascore becomes invisible. I may switch this out for darker rather than lighter.
6. This is intentional, they are in their "disabled" or "inactive" state, they have nothing new to offer so at a quick glance it's obvious which line does when it says "1 New Comment" for example, it's quickly visible.

**Closed as completed** 2016-02-27 14:36 UTC
Labels: question, aesthetic issue
