### ISSUE TITLE
Overlapped Text in settings and in-game overlay

### ISSUE THREAD

**Issue by IluvKats** [DirtDiglett/Pressure2#106] opened 2017-07-09 23:57 UTC
#### Are you using Pressure2 or Pressure2 Dark?
Both but mostly dark

#### Description of the issue.
Overlapped text I'm guessing resolution is causing it but I'm not sure (I'm on 1366x768)
It happens only on Web Browser tab in settings and in-game overlay for both dark and standard

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
I haven't tried the beta

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
I'm using the latest version

### "Allow desktop web browsers to automatically log into Steam sites" is almost completely hidden
![2017-07-10 00_23_56-settings](https://user-images.githubusercontent.com/30029916/27998613-33cd9522-6512-11e7-92b3-abce96349315.png)
### This is how it looks like on the original Pressure
![2017-07-10 00_38_57-steam](https://user-images.githubusercontent.com/30029916/27998615-383dddf6-6512-11e7-90a0-94f09b636190.png)
### View Players is hidden and can't even click it when hovering above it (on the original pressure it's accessible and looks good :)
![payday2_win32_release_2017_07_10_00_29_39_059](https://user-images.githubusercontent.com/30029916/27998675-ef66f0da-6512-11e7-9d3c-1237ad7ad340.png)

#### Steps to reproduce the issue.
N/A

**Comment by FlamingFox911** [comment] 2017-07-10 23:43
A relatively recent feature that has yet to be formatted in Pressure 2.

**Comment by Riiskyy** [comment] 2017-08-05 13:46
Overlapping also occurs on the Friends page within settings

![image](https://user-images.githubusercontent.com/30751766/28995888-cbbcfdd4-79ec-11e7-9a9c-8db62c2b0f87.png)

**Comment by thendarion** [comment] 2018-04-30 10:34
Here's what helped me with the layout:

1. exit steam
2. go to steamclientfolder/skins/pressurefolder/steam/cached/
3. delete those parts you have issues with
4. start steam
5. admire the non-overlapping (though probably less pretty) layout

I know this is a dirty hack at best, but at least it makes the interface readable until a proper fix arrives.

EDIT: apparently this only fixed half of the issues. I guess the root cause is somewhere deeper.

**Comment by DoctorDinosaur** [comment] 2018-05-05 15:08
Fixed the settings in my unofficial patch: https://github.com/CptDinosaur/Pressure2DarkPatch
Can't reproduce the View Players bit, might be your monitor is too small

**Comment by DirtDiglett** [comment] 2018-08-16 09:57
Fixed in Pressure 1.1

**Closed as completed by DirtDiglett** 2018-08-16 09:57 UTC
Labels: in progress
