### ISSUE TITLE
CPU loaded 30% and overall performance is very low

### ISSUE THREAD

**Issue by avsaponchik** [DirtDiglett/Pressure2#27] opened 2016-02-28 16:29 UTC
#### Description of the issue.

Read #StepsToReproduce
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes. Doesn't matter what build.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10 x64
#### Are you using the latest stable release or using the latest commit version?

Synced with git automatically on every steam start
#### A screenshot of the issue.

![default](https://cloud.githubusercontent.com/assets/1337953/13380332/398e585a-de51-11e5-92f6-60da97e14a6e.PNG)
#### Steps to reproduce the issue.

Open your task manager
Open your friend list
Pay attention on CPU load
Scroll your friend list with scroll bar
...
You will have 30% CPU load and overall performance will be low.

**Comment by DirtDiglett** [comment] 2016-02-28 21:55
Thanks for the report, but this is a duplicate of #3 which has been resolved for a 1.0.1 release.

**Closed as completed by DirtDiglett** 2016-02-28 21:55 UTC

**Comment by noddinagushpa** [comment] 2017-02-11 17:36
@DirtDiglett Still got the exact same problem on 1.0.3 :(
![default](https://cloud.githubusercontent.com/assets/25709695/22855966/880cbc76-f0c3-11e6-8c05-c3a2160d5f2a.JPG)
(I was scrolling/Steam CPU rise to about 30% immediately from about 1%/This kind of lag also happens during any other animation)
(Just a guess, if you don't get lag like this without anniversary windows10, then it could be related to some changes in 1611 about directx api?)

**Comment by avsaponchik** [comment] 2017-02-12 10:55
Scrolling the friend list on my laptop cause so many lags... Only with pressure2!
Idk what is wrong with these skins, but pressure1 is acting faster, and the fastest one is still Compact Skin

**Comment by Js41637** [comment] 2017-02-12 11:13
Unfortunately we're not really sure what causes it and that it only affects some people, with such a small group experiencing these issues it's hard to narrow down the problem which means it's unlikely to be fixed.
