### ISSUE TITLE
Skin Animations Are Laggy

### ISSUE THREAD

**Issue by Sydch** [DirtDiglett/Pressure2#28] opened 2016-03-01 21:47 UTC
**Description of the issue**
It seems laggy, when i tried to close Steam window it disappears very slowly.

**Does it also occur on Steam without the skin installed?**
Nope. Also i tried SteamAIR and Metro For Steam, none of them occurs this issue.

**Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?**
I was on Beta, then i opted out. It still occurs.

**What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)**
Windows 10 Pro 64-Bit

**Are you using the latest stable release or using the latest commit version?**
Tried both. Still occurs.

**A screenshot of the issue.**
Can't screenshot an animated thing, sorry :<

**Steps to reproduce the issue.**
Sign In, then it appears.

**Comment by DirtDiglett** [comment] 2016-03-02 00:09
Duplicate of #27 and has been fixed for a 1.0.1 release. Closing.

**Closed as completed by DirtDiglett** 2016-03-02 00:09 UTC
Labels: duplicate

**Comment by Sydch** [comment] 2016-03-07 23:00
It's still occurs after bugfix update.

**Comment by avsaponchik** [comment] 2016-03-08 00:00
Agreed

**Comment by Razzile** [comment] 2016-05-15 11:57
a bit late I know but I still get major lag even on 1.0.1
