### ISSUE TITLE
When used if pushes the CPU use up to 20%,...

### ISSUE THREAD

**Issue by SSadistic** [DirtDiglett/Pressure2#3] opened 2016-02-24 12:15 UTC
...which makes the scroll (for example) on the game list a really messy and buggy. Other skins including Pressure don't push the usage of CPU even to 3-4%.

![2016-02-24_14-11-28](https://cloud.githubusercontent.com/assets/4640551/13285052/0b10c254-db01-11e5-8c67-9ddc40bc4c16.png)

**Comment by Js41637** [comment] 2016-02-24 12:24
I'm not really noticing this, it is true that the CPU is, on average, a bit higher when using Steam with a skin as the basic steam is very bare bones and Skins have a lot going on. My CPU gets up to about 13% when going through lists and clicking on multiple games.

**Comment by SSadistic** [comment] 2016-02-24 12:27
And now try the normal pressure, it doesn't even goes more than 2-3% when idle. Between 2-3% usage and 20%, there is a big difference when scrolling in Steam friends list or library. 
![2016-02-24_14-27-03](https://cloud.githubusercontent.com/assets/4640551/13285342/b6862f06-db02-11e5-9856-479e8728d5c5.png)

**Comment by Js41637** [comment] 2016-02-24 12:31
I guess this really does depend on Processors, I get 2-3% idle with Pressure2 and no more than 13% when going through lists fast and clicking multiple games which is the same as I get in the original pressure.
Are you in Beta or Stable?

**Comment by katanacrimson** [comment] 2016-02-24 12:32
Can reproduce.  Closing all steam windows, I get CPU use back down to nil. Reopening friends list shoots it up to using an entire core (25% on a quad-core, no hyperthreading proc).  Opening the main window doesn't seem to cause it. Just the friends list.  Going to flip back to Pressure 1 and see if that has the same issue.

ED: Yeah, pressure 1 doesn't have this problem...restarting steam back into pressure 2, it looks like when it's rendering the friends list for sure is when this happens.

**Comment by TripleSquare** [comment] 2016-02-24 12:33
**Does it also occur on Steam without the skin installed?**
No

**Are you in the Steam BETA?**
No

**A screenshot of the issue.**
![pressure2_cpuissue](https://cloud.githubusercontent.com/assets/4160612/13285390/9b898c32-dafa-11e5-8ad8-8ad7bc98a496.png)

**Steps to reproduce the issue.**
- download zip from pressureforsteam.com
- unpack to Steam/skins
- Set Steam Skin to Pressure2-1.0
- Restart Steam (open up Friendslist, Shop and Settings)

(If you close your friends-list the CPU usage drops to less than 3%.looks like this is the issue)

CPU: i7-6700k
GPU: 2x GTX 970
RAM: 32GB DDR4-2133
Windows 10 64 Bit

**Comment by katanacrimson** [comment] 2016-02-24 12:38
![steam](http://i.imgur.com/gDDw4Nu.png)

Should drop my specs as well.  i5-6600k, AMD R9 390x with 32GB DDR4.  Using Steam beta and Windows 7 Pro x64.

**Comment by Js41637** [comment] 2016-02-24 12:40
Hmm ok, the CPU does raise quite quickly for me upon opening the friends-list and slightly higher than while using the rest of skin which is definitely odd. It could just be a weird style that Steam doesn't like rendering.

**Comment by nedelko1maks** [comment] 2016-02-24 13:00
![36](https://cloud.githubusercontent.com/assets/17452466/13286047/5a59740e-db07-11e5-8fff-fbb264bdafbe.png)

**Comment by OfficialPoniesFiM** [comment] 2016-02-24 14:56
I was able to reproduce the bug. Scrolling on the shop takes a while.

### Does it also occur on Steam without the skin installed?

No, it doesn't.

### Are you in the Steam BETA?

No, I am not.

### A screenshot of the issue.

![Screenshot of the issue](http://i.imgur.com/4wbV4ex.png)

### Steps to reproduce the issue.

(copy and pasted)
- download zip from pressureforsteam.com
- unpack to Steam/skins
- Set Steam Skin to Pressure2-1.0
- Restart Steam (open up Friendslist, Shop and Settings)

I have an AMD FX-6300, R9 270X, 16 GB of RAM, and Ubuntu 15.10 with Cinnamon nightly.

**Comment by DirtDiglett** [comment] 2016-02-24 23:33
Thanks for the reports, I appreciate the detailed info you guys have provided. There was similar bugs in Pressure1 when it was released and I suspect similar causes, I'll investigate and resolve this as a higher priority bug.

I can't reproduce the bug myself, so I'll rely on you guys to test and confirm issue resolution as I apply fixes, can you guys reply and confirm if you're able to do that for me please :)

**Comment by SSadistic** [comment] 2016-02-25 01:37
I can test it the bugfixed version, no problem.

**Comment by jessb321** [comment] 2016-02-25 04:36
I can reproduce it as well, OS X and Windows. Much higher when friends list is open then when its not.

**Comment by DirtDiglett** [comment] 2016-02-25 09:47
What I'll get you guys to do for me is to isolate to the file that's causing the issue. 

I believe it's being caused by something in either the friends list or the friend panel, so I've created two basic files to test this.

#### Note: It will be ugly. Don't worry it's just temporary to isolate.

I've attached two files, download these somewhere.

[Isolation Files.zip](https://github.com/DirtDiglett/Pressure2/files/146283/Isolation.Files.zip)

We'll do the replace-and-test one at a time. First with friendpanel.layout, copy this and put it in /Pressure2/resource/layout/ and overwrite the existing file, then restart Steam. 

#### Did this fix the problem?

If not, copy the friendsdialog.res and put this in /Pressure2/friends/ and overwrite this file, then restart Steam.

#### Did this fix the problem?

If not, I'll get you to open Steam in Developer mode, by creating a shortcut like this:
![devmode](https://cloud.githubusercontent.com/assets/3527401/13315742/6671a3d2-dbf8-11e5-9bc2-a8b6190aa0f9.PNG)

Then open Steam using this shortcut, you'll have a new tab at the top - "Console", open up whatever windows trigger the 30% CPU usage and then look in Console, provide me with a screenshot of whatever is in there please.

Thanks!

**Comment by TripleSquare** [comment] 2016-02-25 10:56
Okay.
I did create a copy of Pressure2-1.0 inside Steam/skins, then copied **friendpanel.layout** to /Pressure2/resource/layout/ [restarted steam] no change at all.

**Console Log:**

_Failed to init SteamVR because it isn't installed 
System startup time: 15.73 seconds 
CAPIJobRequestUserStats - Server response failed 2 
ExecSteamURL: "steam://open/friends"_

Copied **friendsdialog.res** [while still having friendpanel.layout inside /resource/layout] to /Pressure2/friends/ [restarted steam], max CPU usage is around 5-6% and later drops to ~2%.

**Console Log:**

_Failed to init SteamVR because it isn't installed 
ExecCommandLine: ""C:\Program Files (x86)\Steam\Steam.exe" -dev" 
System startup time: 8.12 seconds 
CAPIJobRequestUserStats - Server response failed 2 
ExecSteamURL: "steam://open/friends"_

Just out of curiosity I went and copied **friendsdialog.res** from the 1.0 zip and replaced it with the one from Isolation Files.zip [restarted steam] and realized it has the same behaviour with and without the custom **friendsdialog.res**. _**max CPU usage is around 5-6% and later drops to ~2%.**_

**Console Log:** 

_Failed to init SteamVR because it isn't installed 
ExecCommandLine: ""C:\Program Files (x86)\Steam\Steam.exe" -dev" 
System startup time: 7.63 seconds 
CAPIJobRequestUserStats - Server response failed 2 
ExecSteamURL: "steam://open/friends"_

I hope this does help you.

CPU: i7-6700k
GPU: 2x GTX 970
RAM: 32GB DDR4-2133
Windows 10 64 Bit
Steam Beta: None!

ps: Github fix ur codeblocks.

**Comment by SSadistic** [comment] 2016-02-25 13:51
- Copy **friendpanel.layout** in /Pressure2/resource/layout/ and overwrite the existing file, then restart Steam.

**Console log**:
_Failed to init SteamVR because it isn't installed
System startup time: 14.58 seconds
Opening joystick XInput Controller_

**Result**: _Failure - CPU still with about 20% of usage_
-  Copy **friendsdialog.res** and put this in /Pressure2/friends/ and overwrite this file, then restart Steam.

**Console log**
_Failed to init SteamVR because it isn't installed
System startup time: 14.15 seconds
Opening joystick XInput Controller_

**Result**: _Success (I guess) - CPU load not more than 1%_

_**My rig:
CPU: FX-6350
GPU: R7 370 4GB
RAM: 8GB DDR3
Windows: Windows 10 64 bit
Steam Beta: None**_

**Comment by ghost** [comment] 2016-02-25 22:32
It's the friendslist that is causing it for me.

Friendslist Not "open" = <1% cpu usage
Friendslist "open" = >15% cpu usage (The % of cpu usage seems quite random though.)

**Does it also occur on Steam without the skin installed?**

No.

**Are you in the Steam BETA?**

Yes.

**A screenshot of the issue.**
Really bad GIF to show it off: https://i.gyazo.com/26deed2b72c4e01a99cd357ed78b890b.gif

**My system:**
**CPU:** i7-2600K
**GPU**: GTX 780
**RAM:** 16GB DDR3
**OS:** Windows 10 Pro 64 bit

I was the guy who reported the cpu usage bug in Pressure1.
Off topic: Keep up the great work!

**Comment by DirtDiglett** [comment] 2016-02-26 11:58
Can you guys please try replacing /Pressure2/friends/friendsdialog.res with the one in the attached zip and confirm this resolves the problem:

[Potential CPU Fix.zip](https://github.com/DirtDiglett/Pressure2/files/148132/Potential.CPU.Fix.zip)

**Comment by Asphira** [comment] 2016-02-26 12:01
Dig dig dig, where is my credit :P anyway the performance issue should now be fixed, both me and Dirt modified the file until it was working.

**Comment by ghost** [comment] 2016-02-26 12:07
I will test it right now :)

Hmm quite weird, when i open the friendslist again my cpu usage goes to about 7-15% still but only for the first 10 minutes or so and then it goes down to <1% :D

**Comment by jessb321** [comment] 2016-02-26 12:07
Its mostly working for me, still spikes up to about 15% or so, but a lot less than before
http://puu.sh/nm2np/3e33827210.png
http://puu.sh/nm2p3/7081fc6605.png

**Closed as completed** 2016-02-27 14:36 UTC
Labels: bug, high priority bug
